#!/bin/bash

pkill -15 -f checksumInotify1.sh
pkill -15 -f checksum_inotifywait
pkill -15 -f checksum.php
pkill -15 -f checksumInotify.sh
pkill -15 -f verify.php
pkill -15 -f verify.sh
pkill -15 -f verifyShare.php
pkill -15 -f verifyDisk.php
pkill -15 -f checksumShare.php
pkill -15 -f verify*.php
pkill -15 -f par2monitor.sh
pkill -15 -f par2create.php
pkill -15 -f checksumPar2

logTime=$(date +"%Y-%m-%d %H-%M-%S")

logBase="/boot/config/plugins/checksum/logs"

commandLog="$logBase/Command-$logTime.txt"
verifyLog="$logBase/Verify-$logTime.txt"
checksumLog="$logBase/Checksum-$logTime.txt"

mkdir -p "/boot/config/plugins/checksum/logs" >/dev/null 2>&1

if [[ -e "/tmp/checksum/log.txt" ]]
then
  sed 's/$/\r/' < "/tmp/checksum/log.txt" > "$commandLog"
fi
if [[ -e "/tmp/checksum/verifylog.txt" ]]
then
  sed 's/$/\r/' < "/tmp/checksum/verifylog.txt" > "$verifyLog"
fi
if [[ -e "/tmp/checksum/checksumLog.txt" ]]
then
  sed 's/$/\r/' < "/tmp/checksum/checksumLog.txt" > "$checksumLog"
fi


rm /tmp/checksum/running > /dev/null 2>&1
rm /tmp/checksum/waiting > /dev/null 2>&1
rm /tmp/checksum/paused > /dev/null 2>&1
rm /tmp/checksumPipe > /dev/null 2>&1
rm /tmp/checksum/par2pipe > /dev/null 2>&1
rm /tmp/checksum/paranoia > /dev/null 2>&1
rm /tmp/checksum/toVerify* > /dev/null 2>&1
rm /tmp/checksum/onDisk* > /dev/null 2>&1
rm /tmp/checksum/sorted* > /dev/null 2>&1
rm /tmp/checksum/toVerifyShort* > /dev/null 2>&1
rm /tmp/checksum/total* > /dev/null 2>&1


/usr/local/emhttp/plugins/checksum/scripts/checksumRemoveCron.php

